defaults: &defaults
  site_url: http://fandango.local
  site_name: Fandango [DEV]
  admin_email: kris.leech@interkonect.com
  admin_name: Kris Leech
  roles: admin, publisher, system
  system_folders: news, links, blog, faqs, pages, deleted
  modules_enabled: pages, news, links, faqs
  

development:
  <<: *defaults
  
test:
  <<: *defaults

staging:
  <<: *defaults
  site_url: http://dev.crc2020.co.uk
  site_name: Fandango [BETA]
  admin_email: kris.leech@interkonect.com
  
production:
  <<: *defaults
  site_url: http://crc2020.co.uk
  site_name: Fandango
  admin_email: kris.leech@interkonect.com
